### ISSUE TITLE
Create presets for analysis

### ISSUE THREAD

**Issue by ntorquet** [ntorquet/lmt_toolkit_analysis#3]
Presets to create:

- [x] General behavior for each individua from a start time to an end time (number of occurence and total time of each event) -> done (#14  )
- [x] Activity (distance travelled) from a start time to an end time (distance for timebins) -> done (#53 )
- [ ] Openfield (one animal behaviors from a start time and for a duration) #56 
- [ ] Dyadic (behaviors of two animals from a start time which could be the end of a pause period and for a duration) #57
- [ ] Complete dyadic experiment (openfield + dyadic phase) #72 
- [ ] Behaviors from night periods #58
- [ ] Behaviors duration per timebin from a start time and for a duration #73
